name: Pre-Release

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - 6.x

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: TEST BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ORG_ACCESS_TOKEN }}

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v1

      - name: Install asdf dependencies
        working-directory: build-tools
        run: |
          asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
          bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
          asdf install

      - name: Install build tool dependencies
        working-directory: build-tools
        run: npm install

      - name: Get version
        id: build_json
        working-directory: build-tools
        run: |
          content=`node -pe 'JSON.parse(process.argv[1]).tag' "$(cat build.json)"`
          echo "::set-output name=BUILD_VERSION::$content"

      - name: Run build process
        working-directory: build-tools
        env:
          RELEASE_PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          APP_REPO_PATH: ${{ github.workspace }}
        run: gulp app --local --head --skip-lint --version=${{ steps.build_json.outputs.BUILD_VERSION }}

      - name: Archive Build files
        uses: actions/upload-artifact@v2
        with:
          name: EE${{ steps.build_json.outputs.BUILD_VERSION }}
          path: build-tools/builds
      
      - name: Set DP version
        run: echo "dp_ver=1" >> $GITHUB_ENV

      - name: Get previous DP tag
        id: prev_tag
        continue-on-error: true
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ExpressionEngine/ExpressionEngine
          prefix: ${{ steps.build_json.outputs.BUILD_VERSION }}-dp.

      - name: Increase DP version
        if: ${{ steps.prev_tag.outcome == 'success' }}
        run: |
          content=`echo "${{ steps.prev_tag.outputs.tag }}" | cut -d "." -s -f 4`
          echo "dp_ver=$(( 1+$content ))" >> $GITHUB_ENV

      - uses: softprops/action-gh-release@v1
        with:
          name: ExpressionEngine ${{ steps.build_json.outputs.BUILD_VERSION }} DP ${{ env.dp_ver }}
          tag_name: ${{ steps.build_json.outputs.BUILD_VERSION }}-dp.${{ env.dp_ver }}
          target_commitish: ${{ github.head_ref }}
          prerelease: true
          draft: true
          body: ExpressionEngine ${{ steps.build_json.outputs.BUILD_VERSION }} developer preview ${{ env.dp_ver }}
          files: |
            build-tools/builds/ExpressionEngine*
            build-tools/builds/signature.txt

      - name: Directory Listing on Failure
        if: failure()
        run: |
          ls -latr
          ls -latr build-tools
          ls -latr build-tools/builds
