name: Release

on:
  push:
    tags:
      - '6.0.4'

jobs:
  build:
    #if: github.base_ref == '6.x'
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v1

      - name: Install asdf dependencies
        working-directory: build-tools
        run: |
          asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
          bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
          asdf install

      - name: Install build tool dependencies
        working-directory: build-tools
        run: npm install

      - name: Run build process
        working-directory: build-tools
        env:
          RELEASE_PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          APP_REPO_PATH: ${{ github.workspace }}
        run: gulp app --local --head --skip-lint --version=${{ steps.tagName.outputs.tag }}

      - name: Archive Build files
        uses: actions/upload-artifact@v2
        with:
          name: EE${{ steps.tagName.outputs.tag }}
          path: build-tools/builds

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build-tools/builds/ExpressionEngine*,build-tools/builds/signature*"
          name: ExpressionEngine ${{ steps.tagName.outputs.tag }}
          allowUpdates: true
          token: ${{ secrets.ORG_ACCESS_TOKEN }}
          body: ExpressionEngine ${{ steps.tagName.outputs.tag }}

      - name: Directory Listing on Failure
        if: failure()
        run: |
          ls -latr
          ls -latr build-tools
          ls -latr build-tools/builds
